### ISSUE TITLE
HTTP redirect to TLS port with 308.

### ISSUE THREAD

**Issue by simonmittag** [simonmittag/j8a#133]
**Is your feature request related to a problem? Please describe.**
you can't hit the server on port 80 it complains

**Describe the solution you'd like**
send a 308 redirect to same URL on TLS port from 2nd HTTP listener. share connection pool.

```
http:
      port: 8080 | no default
      redirecttls: false | default
tls:
      port: 443 | no default
      cert: ... | no default
      key: ... | no default
```

| cfg HTTP port | cfg HTTP redirect to TLS | cfg TLS port | HTTP listenener | TLS listener | HTTP handler | TLS handler |
|--|--|--|--|--|--|--|
| n | n | n | configpanic() | configpanic() | configpanic() | configpanic() |
| n | n | y | off | on | none | proxyhandler() |
| n | y | n | configpanic()  | configpanic() | configpanic() | configpanic() |
| n | y | y | configpanic() | configpanic() | configpanic() |
|  y  |  n  |  n  |  on | off | proxyhandler() | none |
|  y  |  n  |  y  | go on | on | proxyhandler() | proxyhandler() |
|  y |  y  | n  |  configpanic() | configpanic()  | configpanic()  | configpanic()  |
| y | y | y | go on | on | redirecthandler() | proxyhandler |
