### ISSUE TITLE
Jabba does not fall back to default port for chosen scheme if port definition is missing or mistyped.

### ISSUE THREAD

**Issue by petelah** [simonmittag/j8a#199]
**Describe the bug**
When defining resources in config if the scheme port is missing or mistyped, jabba defaults to port 0.

**To Reproduce**
ie:
```yaml
routes:
  - path: /
    resource: main

resources:
    main:
        - labels:
          - main
          url:
            scheme: https://
            host: example.com
            post: 443
```
Jabba will try and connect to `example.com:0` if we run `curl https://jabba-example-address.com/`

**Expected behaviour**
Jabba should check the scheme and if port is not present should default to the scheme common port.

If for example the scheme is `htps://` the default port is 443.

**Desktop (please complete the following information):**
 - OS: MacOS with Jabba running on Amazon Linux 2
